### ISSUE TITLE
Latest neo4j (v5.x) is installed

### ISSUE THREAD

**Issue by kikuomax** [rooteco/tweetscape-streams#51]
When I ran `docker-compose` on the dev branch, the latest version (v5.x) of neo4j was pulled while v4.4 was supposed. Maybe we should specify the version of neo4j in `docker-compose-*.yml` files; i.e., `neo4j:4.4` instead of `neo4j:latest`.

https://github.com/rooteco/tweetscape-streams/blob/66913a9c99327197f395b594904cea840dd8ff11/docker-compose-dev.yml#L22

**Comment by ntorba** [comment]
@kikuomax I ran into some trouble with this today as well... I should have never used latest. 

check out the changes I pushed in this PR: https://github.com/rooteco/tweetscape-streams/pull/52/files#diff-6e72fc85bdf9d7aa207102402a2de7cf7aec4109d2378b66921a5c70d07a4f1f (now available in the dev branch!) 

That should fix your issue. 
I also updated the repo so the apoc jar is in the repo, so you don't have to handle the volume paths manually anymore
